{
	"version": 1672138080,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/meriam-sheet0.png",
		"images/angrybirds-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/meriam2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/sprite6-sheet0.png",
		"media/uwwu.ogg",
		"media/new_uwu.ogg",
		"media/bg-sound.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}